workloads:
  redis:
    replicaCount: 1
  aimragflow:
    replicaCount: 1
  minio:
    replicaCount: 1
  elasticsearch:
    replicaCount: 1
olaresEnv:
  HF_ENDPOINT: ""
  TABLE_AUTO_ROTATE: "false"
  MCP_ENABLED: "false"
  MCP_MODE: "self-host"
  MCP_API_KEY: ""
  EMBEDDING_BATCH_SIZE: "16"
